In [ ]:
צרי מערך באורך 10 של מספרים שלמים רנדומליים בין 1 ל-50 וחשבי את הממוצע של המספרים


In [3]:
pip install numpy


     ---------------------------------------- 0.0/61.0 kB ? eta -:--:--
     ------------------------- ------------ 41.0/61.0 kB 653.6 kB/s eta 0:00:01
     -------------------------------------- 61.0/61.0 kB 819.4 kB/s eta 0:00:00
   ---------------------------------------- 0.0/15.8 MB ? eta -:--:--
   ---------------------------------------- 0.0/15.8 MB 1.4 MB/s eta 0:00:12
   ---------------------------------------- 0.1/15.8 MB 1.3 MB/s eta 0:00:12
    --------------------------------------- 0.2/15.8 MB 1.7 MB/s eta 0:00:10
   - -------------------------------------- 0.5/15.8 MB 3.0 MB/s eta 0:00:06
   -- ------------------------------------- 0.9/15.8 MB 4.0 MB/s eta 0:00:04
   --- ------------------------------------ 1.3/15.8 MB 4.9 MB/s eta 0:00:03
   ---- ----------------------------------- 1.7/15.8 MB 5.5 MB/s eta 0:00:03
   ----- ---------------------------------- 2.2/15.8 MB 6.0 MB/s eta 0:00:03
   ------ --------------------------------- 2.6/15.8 MB 6.4 MB/s eta 0:00:03
   --

ERROR: Could not install packages due to an OSError: [WinError 2] The system cannot find the file specified: 'C:\\Python310\\Scripts\\f2py.exe' -> 'C:\\Python310\\Scripts\\f2py.exe.deleteme'


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [4]:
import numpy as np


In [12]:
arr =  np.random.randint(1, 50,size=10)

arr.mean()

23.0

In [21]:
np.ndim(arr)

1

In [22]:
arr.size

10

In [13]:
arr

array([13, 40, 41, 15,  9, 47,  1, 17,  3, 44])

In [24]:
ar=np.random.randint(10, 100,size=(2,5))
ar.shape

(2, 5)

In [14]:
arr1 =  np.random.randint(1, 10,size=(2,3))
arr2 =  np.random.randint(1,10,size=(2,3))
arr1

array([[7, 7, 1],
       [9, 7, 3]])

In [15]:
arr2

array([[4, 3, 6],
       [3, 4, 1]])

In [16]:
ab = np.add(arr1,arr2)

In [17]:
ab

array([[11, 10,  7],
       [12, 11,  4]])

In [18]:
ab.mean()

9.166666666666666

In [19]:
arr3 =  np.random.randint(1, 100,size=20)
arr3

array([53,  3, 44, 35, 84, 74, 39,  2, 71,  4,  4, 21, 37, 90, 46, 80, 45,
       53, 87, 69])

In [20]:
condition = arr3 > 50
filtered_arr = arr3[condition]
filtered_arr

array([53, 84, 74, 71, 90, 80, 53, 87, 69])

In [ ]:
arr4 =  np.random.randint(1, 50,size=10)
